### ISSUE TITLE
Cannot change classifications while editing details of a model

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#174] opened 2021-06-10 20:53 UTC
The form for editing details of a model allows you to edit the classifiers, but those are not saved after clicking 'save'.

**Comment by pjmonks** [comment] 2021-06-11 07:36
This is a duplicate of issue #172

**Comment by gammonpeter** [comment] 2021-06-11 07:43
This is a duplicate of issue #172

**Closed by gammonpeter** 2021-06-11 07:43 UTC
Labels: bug, duplicate
